# Generated by Django 5.0.4 on 2024-07-04 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insert', models.DateField(auto_now_add=True)),
                ('fecha_update', models.DateField(auto_now=True)),
                ('num_id', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('edad', models.CharField(blank=True, max_length=50)),
                ('edad_categoria', models.CharField(blank=True, max_length=20)),
                ('breed', models.TextField(max_length=50)),
                ('color', models.TextField(max_length=50)),
                ('sex', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=20)),
                ('estado', models.TextField(default='en poseción', max_length=20)),
                ('type', models.CharField(choices=[('para leche', 'Para leche'), ('para venta', 'Para venta'), ('otro', 'Otro')], max_length=20)),
                ('otro_tipo', models.CharField(default='N/A', max_length=20)),
                ('health', models.CharField(choices=[('saludable', 'Saludable'), ('enfermo', 'Enfermo'), ('otro', 'Otro')], max_length=20)),
                ('otra_salud', models.CharField(default='N/A', max_length=20)),
                ('aditional', models.TextField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('img_cow', models.ImageField(blank=True, null=True, upload_to='media/cows/')),
                ('encargado_insert', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_creado', to=settings.AUTH_USER_MODEL)),
                ('encargado_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_actualizado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insert', models.DateField(auto_now_add=True)),
                ('fecha_update', models.DateField(auto_now=True)),
                ('tipo', models.CharField(max_length=20)),
                ('cantidad_leche', models.FloatField()),
                ('vaca', models.CharField(max_length=50)),
                ('tipo_ganado', models.CharField(choices=[('toro', 'Toro'), ('vaca', 'Vaca'), ('ternero', 'Ternero')], max_length=20)),
                ('cantidad_vendidas', models.IntegerField()),
                ('id_vendidas', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('adicional', models.CharField(max_length=100)),
                ('encargado_insert', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produccion_creado', to=settings.AUTH_USER_MODEL)),
                ('encargado_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produccion_actualizada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insert', models.DateField(auto_now_add=True)),
                ('fecha_update', models.DateField(auto_now=True)),
                ('id_animal', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('general', models.CharField(choices=[('sí', 'Sí'), ('no', 'No')], max_length=2)),
                ('nom_vacuna', models.CharField(max_length=20)),
                ('nom_medicamento', models.CharField(max_length=20)),
                ('razon', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=10)),
                ('peso', models.FloatField()),
                ('tipo_inseminacion', models.CharField(choices=[('inseminación artificial', 'Inseminación Artificial'), ('inseminación natural', 'Inseminación Natural')], max_length=50)),
                ('mat_genetico', models.CharField(max_length=20)),
                ('num_crias', models.IntegerField()),
                ('estado', models.CharField(choices=[('saludable', 'Saludable'), ('enferma', 'Enferma')], max_length=10)),
                ('encargado_insert', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_creado', to=settings.AUTH_USER_MODEL)),
                ('encargado_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_actualizada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insert', models.DateField(auto_now_add=True)),
                ('fecha_update', models.DateField(auto_now=True)),
                ('tipo', models.CharField(choices=[('alimento', 'Alimento'), ('medicamento', 'Medicamento'), ('vacuna', 'Vacuna'), ('otro', 'Otro')], max_length=20)),
                ('otro_tipo', models.CharField(default='N/A', max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('medida', models.CharField(max_length=10)),
                ('lote', models.CharField(max_length=50)),
                ('caducidad', models.DateField()),
                ('condicion', models.CharField(choices=[('refrigerado', 'Refrigerado'), ('congelado', 'Congelado'), ('ambiente', 'Ambiente'), ('otro', 'Otro')], max_length=20)),
                ('otra_condicion', models.CharField(default='N/A', max_length=20)),
                ('unidad', models.FloatField()),
                ('total_actual', models.FloatField()),
                ('total', models.FloatField(editable=False)),
                ('encargado_insert', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministro_creado', to=settings.AUTH_USER_MODEL)),
                ('encargado_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suministro_actualizado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insert', models.DateField(auto_now_add=True)),
                ('fecha_update', models.DateField(auto_now=True)),
                ('name', models.TextField(max_length=50)),
                ('cc', models.TextField(max_length=11)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('trabajador', 'Trabajador'), ('veterinario', 'Veterinario')], max_length=20)),
                ('direction', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel', models.TextField(max_length=11)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('encargado_insert', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador_creado', to=settings.AUTH_USER_MODEL)),
                ('encargado_update', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajador_actualizado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
