# Generated by Django 5.0.4 on 2024-07-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0002_animal_peso_trabajador_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='general',
            field=models.CharField(max_length=5),
        ),
    ]
