# Generated by Django 5.0.4 on 2024-07-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0003_alter_registro_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dosis',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.CharField(choices=[('saludable', 'Saludable'), ('enferma', 'Enferma')], default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='general',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AlterField(
            model_name='registro',
            name='mat_genetico',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nom_medicamento',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nom_vacuna',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='num_crias',
            field=models.IntegerField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='peso',
            field=models.FloatField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='razon',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_inseminacion',
            field=models.CharField(choices=[('inseminación artificial', 'Inseminación Artificial'), ('inseminación natural', 'Inseminación Natural')], default='N/A', max_length=50),
        ),
    ]
