# Generated by Django 5.0.4 on 2024-07-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0004_alter_registro_dosis_alter_registro_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='num_crias',
            field=models.CharField(default='N/A', max_length=4),
        ),
        migrations.AlterField(
            model_name='registro',
            name='peso',
            field=models.CharField(default='N/A', max_length=4),
        ),
    ]
