# Generated by Django 5.0.4 on 2024-07-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0005_alter_registro_num_crias_alter_registro_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.CharField(default='Hacer Primer Pesaje', max_length=20),
        ),
    ]
