# Generated by Django 5.0.4 on 2024-07-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granja', '0008_venta_email_cli_venta_nom_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_uni',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
